Tum:Derleme Calistirma

Calistirma:
	.\bin\program.exe
Derleme:Basamak Dugum Sayi SayilarListesi Fonksiyonlar Main Link
Main:
	g++ -I ./include/ -c ./src/Main.cpp -o ./lib/Main.o
Sayi:
	g++ -I ./include/ -c ./src/Sayi.cpp -o ./lib/Sayi.o
SayilarListesi:
	g++ -I ./include/ -c ./src/SayilarListesi.cpp -o ./lib/SayilarListesi.o
Basamak:
	g++ -I ./include/ -c ./src/Basamak.cpp -o ./lib/Basamak.o
Dugum:
	g++ -I ./include/ -c ./src/Dugum.cpp -o ./lib/Dugum.o
Fonksiyonlar:
	g++ -I ./include/ -c ./src/Fonksiyonlar.cpp -o ./lib/Fonksiyonlar.o
Link:
	g++ ./lib/Main.o ./lib/Sayi.o ./lib/SayilarListesi.o ./lib/Dugum.o ./lib/Basamak.o ./lib/Fonksiyonlar.o -o ./bin/program.exe
